// Generated by gencpp from file car_msgs/LidarDetect.msg
// DO NOT EDIT!


#ifndef CAR_MSGS_MESSAGE_LIDARDETECT_H
#define CAR_MSGS_MESSAGE_LIDARDETECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace car_msgs
{
template <class ContainerAllocator>
struct LidarDetect_
{
  typedef LidarDetect_<ContainerAllocator> Type;

  LidarDetect_()
    : header()
    , x()
    , y()
    , z()  {
      x.assign(0.0);

      y.assign(0.0);

      z.assign(0.0);
  }
  LidarDetect_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x()
    , y()
    , z()  {
  (void)_alloc;
      x.assign(0.0);

      y.assign(0.0);

      z.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 8>  _x_type;
  _x_type x;

   typedef boost::array<float, 8>  _y_type;
  _y_type y;

   typedef boost::array<float, 8>  _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::car_msgs::LidarDetect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_msgs::LidarDetect_<ContainerAllocator> const> ConstPtr;

}; // struct LidarDetect_

typedef ::car_msgs::LidarDetect_<std::allocator<void> > LidarDetect;

typedef boost::shared_ptr< ::car_msgs::LidarDetect > LidarDetectPtr;
typedef boost::shared_ptr< ::car_msgs::LidarDetect const> LidarDetectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_msgs::LidarDetect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_msgs::LidarDetect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_msgs::LidarDetect_<ContainerAllocator1> & lhs, const ::car_msgs::LidarDetect_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_msgs::LidarDetect_<ContainerAllocator1> & lhs, const ::car_msgs::LidarDetect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_msgs::LidarDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_msgs::LidarDetect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::LidarDetect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::LidarDetect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::LidarDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::LidarDetect_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_msgs::LidarDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37bef1e1e7f3d7f8ed3b5e27818ef51e";
  }

  static const char* value(const ::car_msgs::LidarDetect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37bef1e1e7f3d7f8ULL;
  static const uint64_t static_value2 = 0xed3b5e27818ef51eULL;
};

template<class ContainerAllocator>
struct DataType< ::car_msgs::LidarDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_msgs/LidarDetect";
  }

  static const char* value(const ::car_msgs::LidarDetect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_msgs::LidarDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[8] x\n"
"float32[8] y\n"
"float32[8] z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::car_msgs::LidarDetect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_msgs::LidarDetect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarDetect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_msgs::LidarDetect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_msgs::LidarDetect_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MSGS_MESSAGE_LIDARDETECT_H
