# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from first_circle_pathplanning/DetectFinal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DetectFinal(genpy.Message):
  _md5sum = "47a5bbb1bcd3f2398868a84a6aefd851"
  _type = "first_circle_pathplanning/DetectFinal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[8] barrels_x
float32[8] barrels_y
float32[8] barrels_z
# int32 color[8]"""
  __slots__ = ['barrels_x','barrels_y','barrels_z']
  _slot_types = ['float32[8]','float32[8]','float32[8]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       barrels_x,barrels_y,barrels_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DetectFinal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.barrels_x is None:
        self.barrels_x = [0.] * 8
      if self.barrels_y is None:
        self.barrels_y = [0.] * 8
      if self.barrels_z is None:
        self.barrels_z = [0.] * 8
    else:
      self.barrels_x = [0.] * 8
      self.barrels_y = [0.] * 8
      self.barrels_z = [0.] * 8

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_8f().pack(*self.barrels_x))
      buff.write(_get_struct_8f().pack(*self.barrels_y))
      buff.write(_get_struct_8f().pack(*self.barrels_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 32
      self.barrels_x = _get_struct_8f().unpack(str[start:end])
      start = end
      end += 32
      self.barrels_y = _get_struct_8f().unpack(str[start:end])
      start = end
      end += 32
      self.barrels_z = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.barrels_x.tostring())
      buff.write(self.barrels_y.tostring())
      buff.write(self.barrels_z.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 32
      self.barrels_x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=8)
      start = end
      end += 32
      self.barrels_y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=8)
      start = end
      end += 32
      self.barrels_z = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=8)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
